// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

// Stores customer information.
type IstanahpCustomer struct {
	ID        int64
	Name      string
	Email     sql.NullString
	Phone     sql.NullString
	Address   sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

// Defines e-commerce platforms sales might originate from.
type IstanahpEcommercePlatform struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

// Tracks the current stock quantity for each product.
type IstanahpInventoryLevel struct {
	ID           int64
	ProductID    int64
	CurrentStock int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// Logs all changes to inventory levels for auditing and historical analysis.
type IstanahpInventoryMovement struct {
	ID                   int64
	ProductID            int64
	MovementTypeID       int64
	QuantityChange       int32
	CurrentStockSnapshot sql.NullInt32
	SourceTransactionID  sql.NullInt64
	SaleItemID           sql.NullInt64
	PurchaseItemID       sql.NullInt64
	SaleReturnID         sql.NullInt64
	UserID               uuid.NullUUID
	Note                 sql.NullString
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

// Defines types of inventory changes (in/out).
type IstanahpInventoryMovementType struct {
	ID          int64
	Name        string
	Description sql.NullString
	IsInbound   bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

// Defines types of payment accepted.
type IstanahpPaymentMethod struct {
	ID           int64
	Name         string
	Description  sql.NullString
	IsCashMethod bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

// Main product catalog with details.
type IstanahpProduct struct {
	ID           int64
	CategoryID   sql.NullInt64
	TaxRateID    sql.NullInt64
	Name         string
	Sku          string
	Barcode      sql.NullString
	Description  sql.NullString
	CostPrice    string
	RetailPrice  string
	ReorderLevel int32
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

// Defines categories for products/items.
type IstanahpProductCategory struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

// Records purchase orders from suppliers.
type IstanahpPurchase struct {
	ID               int64
	PurchaseStatusID int64
	SupplierID       int64
	PaymentMethodID  sql.NullInt64
	UserID           uuid.UUID
	OrderNumber      string
	TransactionDate  time.Time
	TotalAmount      string
	AmountPaid       string
	Note             sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        sql.NullTime
}

// Details of products in a purchase order.
type IstanahpPurchaseItem struct {
	ID            int64
	PurchaseID    int64
	ProductID     int64
	LineItemTotal string
}

// Defines the status of a purchase order.
type IstanahpPurchaseStatus struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

// Configurable templates for printed or digital receipts.
type IstanahpReceiptTemplate struct {
	ID           int64
	Name         string
	HeaderText   sql.NullString
	FooterText   sql.NullString
	AddressLine1 sql.NullString
	AddressLine2 sql.NullString
	Phone        sql.NullString
	Website      sql.NullString
	IsDefault    bool
	PageWidthMm  sql.NullInt32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

// Defines user roles and their permissions.
type IstanahpRole struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

// Records individual sales transactions.
type IstanahpSale struct {
	ID                  int64
	SaleStatusID        int64
	SaleTypeID          int64
	PaymentMethodID     int64
	UserID              uuid.UUID
	CustomerID          sql.NullInt64
	EcommercePlatformID sql.NullInt64
	ServiceCategoryID   sql.NullInt64
	InvoiceNumber       string
	TransactionDate     time.Time
	CustomerDisplayName sql.NullString
	TotalAmount         string
	TotalDiscountAmount string
	TotalTaxAmount      string
	AmountTendered      sql.NullString
	ChangeGiven         sql.NullString
	PaymentAt           sql.NullTime
	Note                sql.NullString
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DeletedAt           sql.NullTime
}

// Details of products sold in a sale transaction.
type IstanahpSaleItem struct {
	ID             int64
	SaleID         int64
	ProductID      int64
	Quantity       int32
	UnitPrice      string
	DiscountAmount string
	LineItemTotal  string
}

// Records product returns for sales transactions.
type IstanahpSaleReturn struct {
	ID             int64
	SaleID         int64
	SaleItemID     int64
	ProductID      int64
	UserID         uuid.UUID
	ReturnDate     time.Time
	Quantity       int32
	ReturnedAmount string
	Reason         string
	IsRestocked    bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
}

// Defines the status of a sales transaction.
type IstanahpSaleStatus struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

// Defines the general type of a sale (e.g., retail, service).
type IstanahpSaleType struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

// Defines categories for service-type sales.
type IstanahpServiceCategory struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

// Stores supplier information.
type IstanahpSupplier struct {
	ID            int64
	Name          string
	ContactPerson sql.NullString
	Phone         sql.NullString
	Email         sql.NullString
	Address       sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
}

// Defines different tax rates applicable to products or sales.
type IstanahpTaxRate struct {
	ID         int64
	Name       string
	Percentage string
	IsDefault  bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  sql.NullTime
}

// Records all payments made for sales (claims) or purchases (debts).
type IstanahpTransactionPayment struct {
	ID              int64
	TransactionType string
	TransactionID   int64
	PaymentMethodID int64
	UserID          uuid.UUID
	Amount          string
	PaymentDate     time.Time
	Note            sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
}

// Manages staff accounts with role-based access.
type IstanahpUser struct {
	ID           uuid.UUID
	RoleID       int64
	Name         string
	Username     string
	PasswordHash string
	Email        sql.NullString
	Phone        sql.NullString
	IsActive     bool
	LastLoginAt  sql.NullTime
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}
