// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countCustomers = `-- name: CountCustomers :one
SELECT COUNT(*) FROM istanahp.customers
WHERE deleted_at IS NULL
`

func (q *Queries) CountCustomers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCustomers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO istanahp.users (role_id, name, username, password_hash, email, phone)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (username) DO NOTHING
RETURNING id, role_id, name, username, password_hash, email, phone, is_active, last_login_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	RoleID       int64
	Name         string
	Username     string
	PasswordHash string
	Email        sql.NullString
	Phone        sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (IstanahpUser, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.RoleID,
		arg.Name,
		arg.Username,
		arg.PasswordHash,
		arg.Email,
		arg.Phone,
	)
	var i IstanahpUser
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.Name,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.Phone,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, description, created_at, updated_at, deleted_at FROM istanahp.roles
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetRoleByID(ctx context.Context, id int64) (IstanahpRole, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, id)
	var i IstanahpRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, role_id, name, username, password_hash, email, phone, is_active, last_login_at, created_at, updated_at, deleted_at FROM istanahp.users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (IstanahpUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i IstanahpUser
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.Name,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.Phone,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, role_id, name, username, password_hash, email, phone, is_active, last_login_at, created_at, updated_at, deleted_at FROM istanahp.users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (IstanahpUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i IstanahpUser
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.Name,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.Phone,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
